apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: ndc-mgmt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-deployment
  template:
    metadata:
      labels:
        app: simple-deployment
        deploymentconfig: simple-deployment
