apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ndc-mgmt-namespace-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: cluster
    repoURL: https://github.com/usunnapu/openshift-gitops-getting-started.git
    targetRevision: mgmt
